// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/product": {
            "post": {
                "summary": "Create a new product",
                "description": "Create a new product with the provided details",
                "tags": ["products"],
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "description": "Product creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/product.CreateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/product.CreateProdutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Get list of products",
                "description": "Get a paginated list of products with optional filters",
                "tags": ["products"],
                "parameters": [
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "SKU",
                        "name": "sku",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by",
                        "name": "sortBy",
                        "in": "query",
                        "enum": ["newest", "oldest", "cheapest", "expensive"]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/product.ProdutListResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/product/{productId}": {
            "put": {
                "summary": "Update an existing product",
                "description": "Update a product with the provided details",
                "tags": ["products"],
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Product update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/product.UpdateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/product.UpdateProdutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a product",
                "description": "Delete a product by its ID",
                "tags": ["products"],
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/purchase": {
            "post": {
                "summary": "Create a purchase",
                "description": "Create a new purchase with items and sender details",
                "tags": ["purchases"],
                "parameters": [
                    {
                        "description": "Purchase creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/purchase.CreatePurchaseReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/purchase.CreatePurchaseResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/purchase/{purchaseId}": {
            "post": {
                "summary": "Upload payment proof for a purchase",
                "description": "Upload proof of payment files for an existing purchase",
                "tags": ["purchases"],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Purchase ID",
                        "name": "purchaseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Upload proof request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/purchase.UploadProofReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "product.CreateProductRequest": {
            "type": "object",
            "required": ["name", "category", "qty", "price", "sku", "fileId"],
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 4,
                    "maxLength": 32
                },
                "category": {
                    "type": "string",
                    "enum": ["Food", "Beverage", "Clothes", "Furniture", "Tools"]
                },
                "qty": {
                    "type": "integer",
                    "minimum": 1
                },
                "price": {
                    "type": "integer",
                    "minimum": 100
                },
                "sku": {
                    "type": "string",
                    "maxLength": 32
                },
                "fileId": {
                    "type": "string"
                }
            }
        },
        "product.CreateProdutResponse": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qty": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "fileId": {
                    "type": "string"
                },
                "fileUri": {
                    "type": "string"
                },
                "fileThumbnailUri": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "product.UpdateProductRequest": {
            "type": "object",
            "required": ["productId", "name", "category", "qty", "price", "sku", "fileId"],
            "properties": {
                "productId": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 4,
                    "maxLength": 32
                },
                "category": {
                    "type": "string",
                    "enum": ["Food", "Beverage", "Clothes", "Furniture", "Tools"]
                },
                "qty": {
                    "type": "integer",
                    "minimum": 1
                },
                "price": {
                    "type": "integer",
                    "minimum": 100
                },
                "sku": {
                    "type": "string",
                    "maxLength": 32
                },
                "fileId": {
                    "type": "string"
                }
            }
        },
        "product.UpdateProdutResponse": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qty": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "fileId": {
                    "type": "string"
                },
                "fileUri": {
                    "type": "string"
                },
                "fileThumbnailUri": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "product.ProdutListResponse": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qty": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "fileId": {
                    "type": "string"
                },
                "fileUri": {
                    "type": "string"
                },
                "fileThumbnailUri": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "purchase.CreatePurchaseReq": {
            "type": "object",
            "required": ["purchasedItems", "senderName", "senderContactType", "senderContactDetail"],
            "properties": {
                "purchasedItems": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/purchase.CreatePurchaseItemReq"
                    }
                },
                "senderName": {
                    "type": "string",
                    "minLength": 4,
                    "maxLength": 55
                },
                "senderContactType": {
                    "type": "string",
                    "enum": ["email", "phone"]
                },
                "senderContactDetail": {
                    "type": "string"
                }
            }
        },
        "purchase.CreatePurchaseItemReq": {
            "type": "object",
            "required": ["productId", "qty"],
            "properties": {
                "productId": {
                    "type": "string"
                },
                "qty": {
                    "type": "integer",
                    "minimum": 2
                }
            }
        },
        "purchase.CreatePurchaseResp": {
            "type": "object",
            "properties": {
                "purchaseId": {
                    "type": "string"
                },
                "purchasedItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/purchase.ProductSnapshotResp"
                    }
                },
                "totalPrice": {
                    "type": "integer",
                    "format": "int64"
                },
                "paymentDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/purchase.PaymentDetailResp"
                    }
                }
            }
        },
        "purchase.ProductSnapshotResp": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "qty": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer",
                    "format": "int64"
                },
                "sku": {
                    "type": "string"
                },
                "fileId": {
                    "type": "string"
                },
                "fileUri": {
                    "type": "string"
                },
                "fileThumbnailUri": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "updatedAt": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "purchase.PaymentDetailResp": {
            "type": "object",
            "properties": {
                "bankAccountName": {
                    "type": "string"
                },
                "bankAccountHolder": {
                    "type": "string"
                },
                "bankAccountNumber": {
                    "type": "string"
                },
                "totalPrice": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "purchase.UploadProofReq": {
            "type": "object",
            "required": ["fileIds"],
            "properties": {
                "fileIds": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Type \"Bearer\" followed by a space and JWT token."
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "TutuPlapak Product Purchase API",
	Description:      "A product purchase API for TutuPlapak",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  doc,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}